### ISSUE TITLE
ios系统中元素被点击时产生的半透明灰色背景区块

### ISSUE THREAD

**Issue by answershuto** [answershuto/webShare#1]
```css
a,button,input{
    -webkit-tap-highlight-color: rgba(0,0,0,0;)
}
```
